include:
  - "*.tsx"
  - "*.ts"

defaults:
  - scope:
      path: "*.tsx"
    values:
      content_type: "application/javascript"
  - scope:
      path: "*.ts"
    values:
      content_type: "application/javascript"
